### ISSUE TITLE
Unhandled panic when connecting to unresponsive server

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/go-libbitcoinclient#1]
I'm assuming libbitcoin1.openbazaar.org is having issues right now. The code panics in the `poll` function in `socket.go`. Not sure whey the panic is thrown as of yet. 

This causes the entire app to crash atm as zmq triggers an os interrupt.

**Comment by hoffmabc** [comment]
Yes libbitcoin1.openbazaar.org I’m still working on.

**Comment by cpacia** [comment]
Do you have any idea what the issue is? I can't get it to stop crashing on my end. Looks like the error might be in the C binding.

**Comment by cpacia** [comment]
I thought I fixed it but I didn't. It was crashing every time before, I made some changes to the threading, now it's only intermittently crashing. Still don't know the reason.
